"""add_scoring_columns_to_videos

Revision ID: 0bbfea8d2a3b
Revises: 1be2cda6002d
Create Date: 2026-02-13 02:31:59.863132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bbfea8d2a3b'
down_revision: Union[str, None] = '1be2cda6002d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('hook_score', sa.Float(), nullable=True))
    op.add_column('videos', sa.Column('velocity', sa.Float(), nullable=True))
    op.add_column('videos', sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'last_analyzed_at')
    op.drop_column('videos', 'velocity')
    op.drop_column('videos', 'hook_score')
    # ### end Alembic commands ###
