"""create core tables

Revision ID: 1be2cda6002d
Revises: 
Create Date: 2026-02-11 21:01:32.729415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be2cda6002d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('channel_title', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_analytics_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creators_channel_id'), 'creators', ['channel_id'], unique=True)
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('youtube_video_id')
    )
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('watch_time_minutes', sa.Integer(), nullable=True),
    sa.Column('average_view_duration', sa.Integer(), nullable=True),
    sa.Column('retention_at_30s', sa.Float(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'snapshot_date'),
    sa.UniqueConstraint('video_id', 'snapshot_date', name='uq_video_date')
    )
    op.create_index('ix_snapshot_date', 'analytics_snapshots', ['snapshot_date'], unique=False)

    # Convert analytics_snapshots to a TimescaleDB hypertable for time-series queries
    op.execute("SELECT create_hypertable('analytics_snapshots', 'snapshot_date', migrate_data => true);")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshot_date', table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    op.drop_table('videos')
    op.drop_index(op.f('ix_creators_channel_id'), table_name='creators')
    op.drop_table('creators')
    # ### end Alembic commands ###
