"""add_view_count_to_videos

Revision ID: 1c7f76f989e3
Revises: 0bbfea8d2a3b
Create Date: 2026-02-13 02:57:31.573035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c7f76f989e3'
down_revision: Union[str, None] = '0bbfea8d2a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('view_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'view_count')
    # ### end Alembic commands ###
