"""phase_2_5_multi_tenant

Revision ID: 4df817618573
Revises: 1c7f76f989e3
Create Date: 2026-02-21 02:50:41.635806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4df817618573'
down_revision: Union[str, None] = '1c7f76f989e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Create the new 'users' table
    op.create_table('users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('firebase_uid', sa.String(length=128), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)

    # 2. Create the new 'youtube_channels' table
    op.create_table('youtube_channels',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('youtube_channel_id', sa.String(length=64), nullable=False),
        sa.Column('channel_name', sa.String(length=255), nullable=True),
        sa.Column('channel_avatar_url', sa.String(length=500), nullable=True),
        sa.Column('access_token', sa.Text(), nullable=True),
        sa.Column('refresh_token', sa.Text(), nullable=True),
        sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_channels_user_id'), 'youtube_channels', ['user_id'], unique=False)
    op.create_index(op.f('ix_youtube_channels_youtube_channel_id'), 'youtube_channels', ['youtube_channel_id'], unique=True)

    # 3. Update 'videos': drop old FK first, then add new column + FK
    op.drop_constraint('videos_creator_id_fkey', 'videos', type_='foreignkey')
    op.drop_column('videos', 'creator_id')
    op.add_column('videos', sa.Column('channel_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_videos_channel_id'), 'videos', ['channel_id'], unique=False)
    op.create_foreign_key('videos_channel_id_fkey', 'videos', 'youtube_channels', ['channel_id'], ['id'], ondelete='CASCADE')

    # 4. Now safe to drop the old 'creators' table
    op.drop_index('ix_creators_channel_id', table_name='creators')
    op.drop_table('creators')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('creator_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.create_foreign_key('videos_creator_id_fkey', 'videos', 'creators', ['creator_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_videos_channel_id'), table_name='videos')
    op.drop_column('videos', 'channel_id')
    op.create_table('creators',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('channel_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('channel_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_expiry', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('next_analytics_sync', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='creators_pkey')
    )
    op.create_index('ix_creators_channel_id', 'creators', ['channel_id'], unique=True)
    op.drop_index(op.f('ix_youtube_channels_youtube_channel_id'), table_name='youtube_channels')
    op.drop_index(op.f('ix_youtube_channels_user_id'), table_name='youtube_channels')
    op.drop_table('youtube_channels')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
